### ISSUE TITLE
Migrate the Java flow example from the DAP conjur-intro repo to a katacoda scenario

### ISSUE THREAD

**Issue by izgeri** [cyberark/katacoda-scenarios#3]
There is an example flow in the `conjurdemos/conjur-intro` repo that builds a Java app that uses the Java client library and deploys it to OpenShift together with Conjur / the Kubernetes authenticator using the helm chart.

This would be a great (and detailed) katacoda flow, and we could also extrapolate it to other language examples.

In addition, since the `conjur-intro` repo is primarily DAP demo flows, we should move the code from there to here, modifying as needed to make this flow generalizable to multiple languages and to work in katacoda. We may also need to use kubernetes instead of openshift for this flow.

The flow in `conjur-intro` is currently in two steps:
- [java client app](https://github.com/conjurdemos/dap-intro/tree/master/demos/java-api-client)
- [openshift deployment](https://github.com/conjurdemos/dap-intro/tree/master/demos/openshift-install)

AC:
- [x] Create a katacoda scenario based on the demo flow linked above, that deploys Conjur OSS via the helm chart to Kubernetes, and then builds and deploys a simple Java app that uses the Java API client authenticating to Conjur via the access token provided by the kubernetes authenticator
- [ ] Remove the Conjur OSS demo flow from the `conjur-intro` repo

**Comment by sgnn7** [comment]
@izgeri I think removing the demo from conjurintros even if it's a duplicate in the end will fragment our demo repos even further than they already are. I'm not sure it's a good path forward for this, especially since we don't have a good plan for moving all conjur intros to there.

**Comment by izgeri** [comment]
`conjurintros` is a DAP-only repo, and the demos in this repo will be able to be published on conjur.org as well as having source available here. it's intended that the OSS demo flows will be primarily in this repo. DAP is a separate question.

**Comment by izgeri** [comment]
closing, since we're opting not to proceed with this katacoda flow for now.
